name = "NumericalDebugging"
uuid = "ee34e48c-26bf-497e-93c0-4433ee141562"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.1.1"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
ForwardDiff = "0.10"
Requires = "1"
julia = "1.6"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ForwardDiff", "Test"]
